eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8093
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /book/**
      serviceId: service-ribbon
    api-b:
      path: /user/**
      serviceId: service-feign-user
